-- CONSULTA #1
SELECT MESA.RESTAURANTE_ID, RESERVA.FECHA_RESERVA, MESA.NOMBRE AS MESA,
		RESERVA.COMENSALES, CLIENTE.NOMBRE AS CLIENTE, CLIENTE.TELEFONO AS TLF_CLIENTE, CLIENTE.EMAIL AS EMAIL_CLIENTE
FROM MESA
		INNER JOIN RESERVA ON RESERVA.MESA_ID = MESA.ID
		INNER JOIN CLIENTE ON CLIENTE.ID = RESERVA.CLIENTE_ID
WHERE MESA.RESTAURANTE_ID = 1 AND DATE(RESERVA.FECHA_RESERVA) = '2024-03-14';

-- CONSULTA #2
SELECT RESTAURANTE.NOMBRE
FROM FAVORITO
		INNER JOIN RESTAURANTE ON RESTAURANTE.ID = FAVORITO.RESTAURANTE_ID
WHERE RESTAURANTE.IS_OPEN = 1 AND FAVORITO.CLIENTE_ID = 1;

-- CONSULTA #3
UPDATE RESERVA
SET FECHA_RESERVA = '2025-04-13 18:00'
WHERE ID = 10;

-- CONSULTA #4
DELETE FROM FAVORITO
WHERE CLIENTE_ID = 1
	AND RESTAURANTE_ID IN (
      SELECT ID FROM RESTAURANTE WHERE IS_OPEN = 0
	);

-- CONSULTA #5
SELECT RESTAURANTE.NOMBRE
FROM RESERVA
	INNER JOIN MESA ON RESERVA.MESA_ID = MESA.ID
	INNER JOIN RESTAURANTE ON MESA.RESTAURANTE_ID = RESTAURANTE.ID
WHERE DATE(RESERVA.FECHA_RESERVA) = '2024-04-01'
  AND RESERVA.COMENSALES >= 4
GROUP BY RESTAURANTE.ID
HAVING COUNT(RESTAURANTE.ID) > 3;

-- CONSULTA #6
SELECT SUM(MAX_COMENSALES) AS AFORO
FROM MESA
WHERE RESTAURANTE_ID = 5;

-- CONSULTA #7
SELECT *
FROM MESA
		WHERE RESTAURANTE_ID = 5
			AND MAX_COMENSALES >= 2
			AND ID NOT IN (
				SELECT MESA_ID
				FROM RESERVA
				WHERE FECHA_RESERVA = '2024-12-31 19:00'
			);

-- CONSULTA #8
SELECT CLIENTE.NOMBRE, COUNT(*) AS NUM_RESERVAS
FROM RESERVA
		INNER JOIN CLIENTE ON CLIENTE.ID = RESERVA.CLIENTE_ID
        INNER JOIN MESA ON MESA.ID = RESERVA.MESA_ID
        INNER JOIN RESTAURANTE ON RESTAURANTE.ID = MESA.RESTAURANTE_ID
WHERE RESTAURANTE.ID = 1
AND DATE(FECHA_RESERVA) BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY CLIENTE.ID
ORDER BY 2 DESC
LIMIT 1;