@host=http://localhost:3000

GET {{host}}/api/products

###
GET {{host}}/api/products/dept/Muebles

###
GET {{host}}/api/products/price/min/50/max/150

###
GET {{host}}/api/products/actives

###
POST {{host}}/api/products
Content-Type: application/json

{
    "name": "Lápiz morado",
    "description": "Pinta mucho en morado, sobre todo",
    "price": 12,
    "stock": 100,
    "department": "office",
    "available": true
}

###
PUT {{host}}/api/products/6836034d03f3ded08a79d18c
Content-Type: application/json

{
    "price": 40,
    "stock": 3000
}

###
DELETE {{host}}/api/products/6836034d03f3ded08a79d18c


########
# USERS#
########

POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "Pepito el de los palotes",
    "email": "pepito.palotes@example.com",
    "password": "123456",
    "role": "admin"
}

###

POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "pepito.palotes@example.com",
    "password": "123456"
}