@host=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjgzNzU2NDJlNGZmODA1YzIzODIwNmNlIiwiZXhwIjoxNzQ4NTQ1OTQzLCJpYXQiOjE3NDg1NDUwNDN9.myrnHjk8vjQndhVd_TN5w87JfPjM4XKkFY9UdlISMTs

GET {{host}}/api/products
Authorization: {{token}}

###
GET {{host}}/api/products/dept/Informática
Authorization: {{token}}

###
GET {{host}}/api/products/price/min/50/max/150

###
GET {{host}}/api/products/actives

###
POST {{host}}/api/products
Content-Type: application/json
Authorization: {{token}}

{
    "name": "iPhone 32 X Pro",
    "description": "Un teléfono que además llama",
    "price": 2600,
    "stock": 12,
    "department": "Informática",
    "available": true
}

###
PUT {{host}}/api/products/6836034d03f3ded08a79d18c
Content-Type: application/json

{
    "price": 40,
    "stock": 3000
}

###
DELETE {{host}}/api/products/6836034d03f3ded08a79d18c


########
# USERS#
########

POST {{host}}/api/users/register
Content-Type: application/json

{
    "username": "Pepito el de los palotes",
    "email": "pepito.palotes@example.com",
    "password": "123456",
    "role": "admin"
}

###

POST {{host}}/api/users/login
Content-Type: application/json

{
    "email": "pepito.palotes@example.com",
    "password": "123456"
}

###
PATCH {{host}}/api/users/addCart
Authorization: {{token}}
Content-Type: application/json

{
    "productId": "683745b69070c6adb8317d67"
}

###
GET {{host}}/api/users/me
Authorization: {{token}}